name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set Go Cache Directory
        run: |
          mkdir -p $HOME/go-cache
          mkdir -p $HOME/go-mod-cache
        env:
          GOCACHE: $HOME/go-cache
          GOMODCACHE: $HOME/go-mod-cache

      - name: Cache Go Modules
        uses: actions/cache@v4
        with:
          path: |
            $HOME/go-cache
            $HOME/go-mod-cache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        run: go mod tidy

      - name: Build
        run: go build -o ./bin/fusion ./cmd

      - name: Test
        run: go test -v ./...
